os: osx
language: generic
sudo: true

addons:
  homebrew:
    packages:
        # coreutils for gtimeout command
        - coreutils

install:

#######################################
# Move files

- sudo mkdir -p /Library/LaunchDaemons/
- sudo mv pf/pf.conf /etc/pf.conf
- sudo mv pf/security.pf.plist /Library/LaunchDaemons/security.pf.plist
- sudo mv pf/security.pflog0create.plist /Library/LaunchDaemons/security.pflog0create.plist
- sudo mv pf/security.pflog0dump.plist /Library/LaunchDaemons/security.pflog0dump.plist

#######################################
# Set permission to pf.conf

- sudo chmod 644 /etc/pf.conf

#######################################
# start configuration

- sudo /sbin/pfctl -E -f /etc/pf.conf

script:
- bash ./test/check.sh 